### ISSUE TITLE
0.2.4.0 fails to build with GHC-7.8 and older

### ISSUE THREAD

**Issue by phadej** [HeinrichApfelmus/operational#30]
```
[1 of 1] Compiling Control.Monad.Operational ( src/Control/Monad/Operational.hs, /codetmp/oper/operational-0.2.4.0/.dist-newstyle-trustee/aa6ee86615bf83600e1a9cc59f3dab339d9b62d6eacba769f14a98fa1bfef1944c916e7d0697650e9fa9296f78441ac1098d8bdc832acfacbda4516e021f32e3/build/x86_64-linux/ghc-7.8.4/operational-0.2.4.0/noopt/build/Control/Monad/Operational.o )


src/Control/Monad/Operational.hs:215:21:
    Not in scope: type constructor or class ‘Applicative’

src/Control/Monad/Operational.hs:241:21:
    Not in scope: type constructor or class ‘Applicative’
cabal: Failed to build operational-0.2.4.0 (which is required by
exe:operational-TicTacToe from operational-0.2.4.0).
```

I made a revision to disallow old `base`: https://hackage.haskell.org/package/operational-0.2.4.0/revisions/

**Comment by HeinrichApfelmus** [comment]
I have uploaded a new release:

https://hackage.haskell.org/package/operational-0.2.4.1

Thanks for the heads-up!

**Comment by phadej** [comment]
Please read through https://github.com/haskell-infra/hackage-trustees/blob/master/revisions-information.md

The release you made was completely unnecessary. Without a revision on 0.2.4.0 (which I did) it wouldn't even fix the issue (third section in the revisions info). With a revision, 0.2.4.1 s an exact copy of revised 0.2.4.0:

```
% cabal get operational-0.2.4.0
% cabal get operational-0.2.4.1
% diff -ur operational-0.2.4.0 operational-0.2.4.1
diff -ur operational-0.2.4.0/CHANGELOG.md operational-0.2.4.1/CHANGELOG.md
--- operational-0.2.4.0/CHANGELOG.md	2001-09-09 04:46:40.000000000 +0300
+++ operational-0.2.4.1/CHANGELOG.md	2001-09-09 04:46:40.000000000 +0300
@@ -1,6 +1,10 @@
 Changelog for the `operational` package
 ---------------------------------------
 
+**0.2.4.1** -- Maintenance release.
+
+* Restrict dependencies to ensure GHC >= 7.10.
+
 **0.2.4.0** -- Feature release.
 
 * Update to build with GHC 9.0.1.
diff -ur operational-0.2.4.0/operational.cabal operational-0.2.4.1/operational.cabal
--- operational-0.2.4.0/operational.cabal	2021-11-07 16:43:20.021972866 +0200
+++ operational-0.2.4.1/operational.cabal	2021-11-07 16:40:49.111420181 +0200
@@ -1,6 +1,5 @@
 Name:               operational
-Version:            0.2.4.0
-x-revision: 1
+Version:            0.2.4.1
 Synopsis:           Implementation of difficult monads made easy
                     with operational semantics.
 Description:
```

**Comment by HeinrichApfelmus** [comment]
Oh. Sorry about making the unnecessary release — it's been a long time since I've made a release, and I forgot most of the procedures.
